* py-autopep8.el

[[https://travis-ci.org/paetzke/py-autopep8.el][https://travis-ci.org/paetzke/py-autopep8.el.svg?branch=master]]
[[http://melpa.org/#/py-autopep8][http://melpa.org/packages/py-autopep8-badge.svg]]

Provides the =py-autopep8= command, which uses the external =autopep8= tool to tidy up the current buffer according to Python's PEP8.

Install =autopep8= and download =py-autopep8.el=

#+BEGIN_SRC bash
$ pip install autopep8
$ wget http://git.vanneva.com/py-autopep8.el.git/blob_plain/HEAD:/py-autopep8.el \
       -O /your/path/py-autopep8.el
#+END_SRC

Add the before-save-hook to your ~/.emacs

#+BEGIN_SRC lisp
(add-to-list 'load-path "/your/path/")
(require 'py-autopep8)
(add-hook 'before-save-hook 'py-autopep8-before-save)
#+END_SRC

You can also install py-autopep8 with MELPA:

#+BEGIN_SRC lisp
M-x package-install RET
py-autopep8 RET
#+END_SRC

Now every time you save your Python file autopep8 will be executed on the current buffer.

To customize the behaviour of "autopep8" you can set the py-autopep8-options e.g.

#+BEGIN_SRC lisp
(setq py-autopep8-options '("--max-line-length=100"))
#+END_SRC


** CREDITS

Thanks to:

- Airead (https://github.com/Airead) for testing.
- Fredrik Bergroth
- Yasuyuki Oka (https://github.com/yasuyk) for committing a patch.


** CHANGELOG

*** 0.5
- Fixed typo.

*** 0.4
- Replaced incf and decf.

*** 0.3
- Added check if =autopep8= executable is present.

*** 0.2
- Added options to change =autopep8='s behaviour.

*** 0.1
- Renamed functions: This will break your code.



Copyright (c) 2013-2014, Friedrich Paetzke (paetzke@fastmail.fm). All rights reserved.
